### PR TITLE
Add failbot logging

### PR DESCRIPTION
**Pull request by tmm1**
should make it easier to debug nugget failures in the future

### CODE REVIEW

**Comment by joewilliams** [comment]
Thanks @tmm1!

**Comment by tmm1** [comment]
Trying to figure out how to simulate an exception so I can verify it shows up on https://haystack.githubapp.com/nugget

**Comment by technicalpickles** [comment]
What about adding an option like --boom that raises an error?

**Comment by tmm1** [comment]
Was able to verify this via the exit_hook.

**Pull request merged**
